apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stock-data-streamer.fullname" . }}
  labels:
    {{- include "stock-data-streamer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "stock-data-streamer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "stock-data-streamer.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "stock-data-streamer.serviceAccountName" . }}
      containers:
        - name: stock-data-streamer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
