apiVersion: v1
kind: Service
metadata:
  name: {{.Values.fullNameOverride}}
spec:
  type: "ClusterIP"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
      name: http
  selector:
    app: {{.Values.fullNameOverride}}

