apiVersion: v1
kind: Service
metadata:
  name: {{ include "stock-data-streamer.fullname" . }}
  labels:
    {{- include "stock-data-streamer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    {{- include "stock-data-streamer.selectorLabels" . | nindent 4 }}
