{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stock-data-streamer.serviceAccountName" . }}
  labels:
    {{- include "stock-data-streamer.labels" . | nindent 4 }}
{{- end }}