replicaCount: 1

image:
  repository: ghcr.io/Investment-Alert-System/stock-data-streamer/app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

serviceAccount:
  create: true
  name: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
